### ISSUE TITLE
Option to skip release unless there are some interesting changes

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/jenkins-maven-cd-action#1]
Halfway between manual deployment and CD on every commit, would be nice to have an option to do a deployment iff Release Drafter has found at least one entry that is a feature or bug fix or whatever, as opposed to only `internal`/`chore` or `dependencies` changes.

**Comment by timja** [comment]
Dependencies and internal changes sometimes sometimes require releases though so hard to make this a hard rule

**Comment by jglick** [comment]
True, so this check should be bypassed if `$GITHUB_EVENT_NAME = workflow_dispatch` (as opposed to `status`), so you can include both triggers in your `on` section and explicitly ask to release a particular Dependabot PR or whatever if it is significant.
