### ISSUE TITLE
Define reusable workflow

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/jenkins-maven-cd-action#10]
Can https://github.blog/changelog/2021-10-05-github-actions-dry-your-github-actions-configuration-by-reusing-workflows/ be used to combine this action, https://github.com/jenkins-infra/verify-ci-status-action, and https://github.com/jenkins-infra/interesting-category-action into one reusable workflow rather than forcing every repo to copy all of https://github.com/jenkinsci/.github/blob/ac892e4a1a6bec7b125d25cca2c826d4fef6f9c5/workflow-templates/cd.yaml#L11-L59?

**Comment by jetersen** [comment]
I have written a couple of reusable workflows some open source:
https://github.com/specshell/.github/blob/main/.github/workflows/dotnet-build.yml
https://github.com/cellpointdigital/.github/blob/main/.github/workflows/docker-build.yml usage of docker build: https://github.com/cellpointdigital/pgbouncer-image/blob/main/.github/workflows/docker-build.yml

I'd suggest we keep them in a separate repository so not sure who I need to ask for a reusable workflow repository inside `jenkins-infra`

The reason for the workflows located inside `.github/workflows` is so Dependabot would pick up action updates 😅

**Comment by timja** [comment]
Just create a ticket in the help desk repo of this org

**Comment by jetersen** [comment]
@timja https://github.com/jenkins-infra/helpdesk/issues/2926

**Comment by jglick** [comment]
⇒ https://github.com/jenkins-infra/github-reusable-workflows and thank you in advance!

**Comment by jetersen** [comment]
I'll use my Friday which is national holiday 😅 Tomorrow will be too busy.

**Comment by jetersen** [comment]
https://github.com/jenkins-infra/github-reusable-workflows/pull/1
[jenkinsci/gitlab-api-plugin/.github/workflows/cd.yml](https://github.com/jenkinsci/gitlab-api-plugin/blob/master/.github/workflows/cd.yml)

**Comment by jglick** [comment]
@timja we have a dummy plugin somewhere just for testing CD workflow changes right? Can never remember where…

**Comment by jetersen** [comment]
@jglick already tested: https://github.com/jenkins-infra/github-reusable-workflows/pull/1#issuecomment-1125696191

**Comment by timja** [comment]
It's here: https://github.com/jenkinsci/jenkins-infra-test-plugin

**Comment by jglick** [comment]
Released!
