### ISSUE TITLE
Failed release due to Release Drafter problem

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/jenkins-maven-cd-action#18]
https://github.com/jenkinsci/credentials-plugin/runs/5704515533?check_suite_focus=true#step:4:178 failed apparently because https://github.com/jenkinsci/credentials-plugin/releases/tag/untagged-54e4e6a492aa2a52dac7 was named `1074.1` rather than `next` as expected despite https://github.com/jenkinsci/credentials-plugin/blob/32810fbc0f2f78ebd5d7fb6d8aa4e778fad1e780/.github/workflows/cd.yaml#L27-L29. I needed to manually edit the release to show https://github.com/jenkinsci/credentials-plugin/releases/tag/1087.v16065d268466 as published. Not sure what went wrong—some bug in RD? @timja any clue?

**Comment by timja** [comment]
not seen before.

suspicious that it's released as release-drafter though so it's using the app?

**Comment by jglick** [comment]
Hmm, that could be it. I do not see it in https://github.com/apps/release-drafter/installations/775283 but then again I lack admin access to `credentials-plugin` so maybe it is there. After the wave of PRs replacing the App with a workflow, should we not simply remove this App from the org to avoid confusion and collisions? So convert into a helpdesk ticket?

So far https://github.com/jenkinsci/credentials-plugin/releases/tag/untagged-9b93d56c1b424d0ffa2b is shown as `next` as expected:

> @[github-actions](https://github.com/apps/github-actions) github-actions drafted this 6 minutes ago

**Comment by timja** [comment]
I've suspended the installation of release drafter, we can re-activate it if we need and the list of repoes is still there.

and yes credentials-plugin is on the list

**Comment by jglick** [comment]
OK, so assuming that will solve the problem.
