### ISSUE TITLE
Version extraction is not working correctly

### ISSUE THREAD

**Issue by forgedhallpass** [jenkins-infra/jenkins-maven-cd-action#6]
With the following pom.xml config:
```xml
<version>${revision}${changelist}</version>
...
<properties>
        <revision>1.0.0</revision>
        <changelist>-SNAPSHOT</changelist>
...
```
The following command both locally and in the GitHub workflow, evaluates to `1.0.0-SNAPSHOT` instead of `1.0.0`
```bash
version=$(mvn -B -ntp -Dset.changelist -Dexpression=project.version -q -DforceStdout help:evaluate)
```
making the action unusable.

I want(ed) to make an automated release workflow that is triggered only manually without relying on "interesting categories" extracted from the commit messages. Would be nice to support such a scenario..

**Comment by jglick** [comment]
Currently this action only supports repositories updated to use JEP-229 metadata.
